### ISSUE TITLE
x3 doesnt generate x3 ini

### ISSUE THREAD

**Issue by Choxieota** [n00mkrad/flowframes#214]
Tried to convert a video using x3, with a limit of 60 for the output, got this error:

Generating frame order information for 3x...
Error generating frame order information: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)

   at Flowframes.Main.FrameOrder.<CreateEncFile>d__10.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   at Flowframes.Main.FrameOrder.<CreateFrameOrderFile>d__7.MoveNext()

**Comment by Choxieota** [comment]
After the third restart of flowframes it worked just fine.  Not sure what happened or how to reproduce it.

**Comment by n00mkrad** [comment]
Version?

**Comment by Choxieota** [comment]
1.40.0  Could it have been because I clicked the button labelled "make
output match input duration"?  I also found a note recommending x2, x4,
etc... all with even numbers.  Pretty sure I was just using it wrong.
