### ISSUE TITLE
[1.40.0] Frame extraction failed!

### ISSUE THREAD

**Issue by Nightwolf607** [n00mkrad/flowframes#258]
Hey, 
NMKD said multiple times that this issue was fixed in the latest codebase, but I compiled it myself and it's still happening.
`
[00000000] [08-05-2023 18:21:55]: Cleanup: Session folder 2023-8-5-18-21-54-661 is 0 days old and has 0 files - Will Delete
[00000001] [08-05-2023 18:21:55]: Command Line: "C:\Users\lostb\Downloads\flowframes-main (1)\flowframes-main\Code\bin\Debug\Flowframes.exe" 
[00000002] [08-05-2023 18:21:55]: Files: None
[00000003] [08-05-2023 18:21:55]: Args: None
[00000004] [08-05-2023 18:21:57]: Initialized Nvidia API. GPU: NVIDIA GeForce GTX 1080 Ti
[00000005] [08-05-2023 18:21:57]: [UI] Error getting installed version!
[00000006] [08-05-2023 18:21:57]: Index was outside the bounds of the array.
[00000007] [08-05-2023 18:21:57]: Error getting installed version!
[00000008] [08-05-2023 18:21:57]: Index was outside the bounds of the array.
[00000009] [08-05-2023 18:21:57]: SymlinksAllowed: True
[00000010] [08-05-2023 18:21:57]: Checking if system Python is available...
[00000011] [08-05-2023 18:21:57]: [DepCheck] CMD: /C python -V
[00000012] [08-05-2023 18:21:57]: Parsing Patrons from CSV...
[00000013] [08-05-2023 18:21:57]: Found 33 Gold Patrons, 702 Silver Patrons
[00000014] [08-05-2023 18:21:57]: [DepCheck] System Python Check Output: Python 3.8.6
[00000015] [08-05-2023 18:21:57]: [DepCheck] Sys Python Ver: Python 3.8.6
[00000016] [08-05-2023 18:21:57]: Using Python installation: Python 3.8.6
[00000017] [08-05-2023 18:21:57]: [DepCheck] CMD: "/C" python -u -c "import torch; print(torch.__version__)"
[00000018] [08-05-2023 18:21:57]: [UI] You are running Flowframes 0.0.0. The latest Patreon version is 1.40.0, the latest free version is 1.36.0.
[00000019] [08-05-2023 18:21:57]: [GetGpus] Found GPU: NVIDIA GeForce GTX 1080 Ti
[00000020] [08-05-2023 18:21:57]: [GetGpus] Found GPU: AMD Radeon(TM) Vega 8 Graphics
[00000021] [08-05-2023 18:21:58]: [Servers] Ping to nmkd-hz.de: 144 ms
[00000022] [08-05-2023 18:21:58]: [Servers] Ping to nmkd-cb.de: 57 ms
[00000023] [08-05-2023 18:21:58]: [Servers] Closest Server: USA (St. Louis) (57 ms)
[00000024] [08-05-2023 18:21:59]: [BgTaskMgr] BackgroundTaskManager is busy - 0 tasks running.
[00000025] [08-05-2023 18:22:00]: [DepCheck] Pytorch Check Output: 1.8.1+cu111
[00000026] [08-05-2023 18:22:01]: MessageBox: Unhandled Thread Exception! Cannot access a disposed object.
Object name: 'TextBox'. Stack Trace: at System.Windows.Forms.Control.CreateHandle()
at System.Windows.Forms.TextBoxBase.CreateHandle()
at System.Windows.Forms.TextBox.get_PasswordChar()
at System.Windows.Forms.TextBox.get_PasswordProtect()
at System.Windows.Forms.TextBoxBase.get_CanEnableIme()
at System.Windows.Forms.Control.VerifyImeRestrictedModeChanged()
at System.Windows.Forms.TextBoxBase.set_ReadOnly(Boolean value)
at Flowframes.Forms.Main.Form1.aiCombox_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\lostb\Downloads\flowframes-main (1)\flowframes-main\Code\Forms\Main\Form1.cs:line 525
at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
at Flowframes.Forms.Main.Form1.InitAis() in C:\Users\lostb\Downloads\flowframes-main (1)\flowframes-main\Code\Forms\Main\Form1.cs:line 330
at Flowframes.Forms.Main.Form1.<Form1_Shown>d__16.MoveNext() in C:\Users\lostb\Downloads\flowframes-main (1)\flowframes-main\Code\Forms\Main\Form1.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() The error has been copied to the clipboard. Please inform the developer about this. (Error)`

**Comment by nullkid10** [comment]
no, idk what's going on, seems to be ffmpeg though

**Comment by qmarsn** [comment]
Bump. Happened to me too:

Unhandled Thread Exception!

Could not find file 'C:\flowframes\Flowframes\Flowframes\Flowframes\FlowframesData\logs\2023-12-27-2-30-18-404\.txt'.

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Flowframes.Os.AiProcess.<AiFinished>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Os.AiProcess.<RunRifeNcnn>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Interpolate.<RunAi>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Interpolate.<Start>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Form1.<runBtn_Click>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

The error has been copied to the clipboard. Please inform the developer about this.
