### ISSUE TITLE
FlowFrames Interpolated 0 Frames. Considerd it done.

### ISSUE THREAD

**Issue by badbeef** [n00mkrad/flowframes#312]
Fresh install. 1.36.0. Windows 10. Intel GPU. Tried RIFE (NCNN) and DAIN (NCNN) 

Every time, it will simply say:

Running RIFE (NCNN)...
**Interpolated 0/347 Frames (0%) - Average Speed: 0.00 FPS In / 0.00 FPS Out - Time: 89ms - ETA: 08s**
Done running RIFE - Interpolation took 92ms. Peak Output FPS: 0.00

![image](https://github.com/n00mkrad/flowframes/assets/7761874/e82bc94c-8569-4e34-aac2-f9b44840e949)

What am I missing?

**Comment by badbeef** [comment]
When I try individual step. I got this exception during interpolation.
```

Unhandled Thread Exception!

Could not find file 'C:\Users\me\AppData\Local\Flowframes\FlowframesData\logs\.txt'.

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Flowframes.Os.AiProcess.<AiFinished>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Os.AiProcess.<RunRifeNcnn>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Interpolate.<RunAi>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Main.InterpolateSteps.<InterpolateStep>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Main.InterpolateSteps.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Form1.<runStepBtn_Click>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

I manually created a ".txt" file. And ran it again, this time, it just says:

`Canceled: Interpolation failed - No interpolated frames were created. Last 10 log lines: Check the log '' for more details.`

**Comment by badbeef** [comment]
I tried manually running Interpolation and I got this error:

```
Unhandled Thread Exception!

Could not find file 'C:\Users\store\AppData\Local\Flowframes\FlowframesData\logs\.txt'.

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Flowframes.Os.AiProcess.<AiFinished>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Os.AiProcess.<RunRifeNcnn>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
...

I manually created a `.txt` file. And I ended up with

`Canceled: Interpolation failed - No interpolated frames were created. Last 10 log lines: Check the log '' for more details.`

There is no logs in that `.txt` file.

**Comment by badbeef** [comment]
Found the issue! The system does not have proper video driver installed and it is still using the generic Microsoft video driver. As a result, it is missing all the vulkan dll libraries.
