### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 86102092800 bytes. Buy new RAM!

### ISSUE THREAD

**Issue by BlankFX1** [n00mkrad/flowframes#315]
```
---------------------------
Error
---------------------------
A python error occured during interpolation!
Check flavr-cuda-log for details.

[E] RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:73] data. DefaultCPUAllocator: not enough memory: you tried to allocate 86102092800 bytes. Buy new RAM!
---------------------------
OK   
---------------------------

```
And

```
[3098] [4-19-2024 12:23:17]: Changing working dir to T:\Tools\Flowframes\FlowframesData\pkgs\flavr-cuda
[3099] [4-19-2024 12:23:17]: Added T:\Tools\Flowframes\FlowframesData\pkgs\flavr-cuda to temporary PATH
[3100] [4-19-2024 12:23:22]: [E] flavr.py:90: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:141.)
[3101] [4-19-2024 12:23:22]: [E] images = [torch.Tensor(np.asarray(Image.open(os.path.join(path, f)))).type(torch.uint8) for f in in_files]
[3112] [4-19-2024 12:25:55]: torch.Size([1080, 1920, 3])
[3113] [4-19-2024 12:25:55]: [E] Traceback (most recent call last):
[3114] [4-19-2024 12:25:55]: [E] File "flavr.py", line 101, in <module>
[3115] [4-19-2024 12:25:55]: [E] videoTensor = files_to_videoTensor(interp_input_path)
[3116] [4-19-2024 12:25:55]: [E] File "flavr.py", line 92, in files_to_videoTensor
[3117] [4-19-2024 12:25:55]: [E] videoTensor = torch.stack(images)
[3118] [4-19-2024 12:25:55]: [E] RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:73] data. DefaultCPUAllocator: not enough memory: you tried to allocate 86102092800 bytes. Buy new RAM!
```

Apparently 128 GiB RAM isn't enough for a simple 1080p-Video.
First time using Flowframes (v1.36.0) instead of SVP4.
Tried to go from 23,97602 FPS to x4.

**Comment by 1Noia** [comment]
Same error here, 3080Ti and 32gb but only with FLAVR
