### ISSUE TITLE
Error when de-dublicating a ps5's captured footage

### ISSUE THREAD

**Issue by I3ordo** [n00mkrad/flowframes#339]
Unhandled Thread Exception!

no decode delegate for this image format `DB' @ error/constitute.c/ReadImage/562

Stack Trace:
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(IMagickSettings`1 settings)
   at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings`1 readSettings, Boolean ping)
   at ImageMagick.MagickImage..ctor(String fileName)
   at Flowframes.Magick.Dedupe.GetImage(String path)
   at Flowframes.Magick.Dedupe.GetDifference(String img1Path, String img2Path)
   at Flowframes.Magick.Dedupe.<RemoveDupeFrames>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Magick.Dedupe.<Run>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Interpolate.<PostProcessFrames>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Main.InterpolateSteps.<ExtractFramesStep>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Main.InterpolateSteps.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Flowframes.Form1.<runStepBtn_Click>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

The error has been copied to the clipboard. Please inform the developer about this.

**Comment by I3ordo** [comment]
You are running Flowframes 1.36.0. The latest Patreon version is 1.39.0, the latest free version is 1.36.0
